# Generated by Django 4.1.6 on 2023-02-04 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=10)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('activity', models.CharField(choices=[('1,2', 'Сидячий образ жизни.'), ('1,375', 'До трех малоинтенсивных тренировок в неделю.'), ('1,55', 'Тренировки три-четыре раза в неделю, тренировки интенсивные, но не тяжелые.'), ('1,7', 'Ежедневные занятия спортом или ежедневная работа, связанная с большим количеством перемещений и ручного труда.'), ('1,9', 'Экстремальная активность. Профессиональный спортсмен или работа с тяжестями и т.д.')], default='', max_length=50)),
                ('lactose', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
