# Generated by Django 4.1.6 on 2023-02-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanced_diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_param',
            name='lactose',
        ),
        migrations.RemoveField(
            model_name='user_param',
            name='vegan',
        ),
    ]
