# Generated by Django 4.1.6 on 2023-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanced_diet', '0006_dish_product_user_exclusion_products_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
