# Generated by Django 4.1.6 on 2023-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanced_diet', '0007_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipetext',
            field=models.TextField(default=''),
        ),
    ]
