# Generated by Django 4.1.6 on 2023-03-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanced_diet', '0008_dish_recipetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='amountofprod',
            field=models.CharField(default='', max_length=50),
        ),
    ]
