# Generated by Django 4.1.6 on 2023-03-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanced_diet', '0011_user_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_nutrition',
            name='meal',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('BR', 'Brunch'), ('LN', 'Lunch'), ('DN', 'Dinner')], default='', max_length=10),
        ),
    ]
